UniversityManagementSystem06/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem06.BusinessLogics.Course;
using UniversityManagementSystem06.Models;

namespace UniversityManagementSystem06.Controllers
{
    public class CourseController : Controller
    {
        CourseManager aCourseManager = new CourseManager();


        // GET: Course
        [HttpGet]
        public ActionResult SaveCourse()
        {
            List<DepartmentModel> departmentList = aCourseManager.GetDepartmentList();
            List<SemesterModel> semesterList = aCourseManager.GetAllSemesters();
            ViewBag.departmentList = departmentList;
            ViewBag.semesterList = semesterList;
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(CourseModel aCourseModel)
        {
            string message = "";
            message = aCourseManager.SaveCourse(aCourseModel);
            ViewBag.Message = message;
            //List<string> departmentCodeList = aCourseManager.GetDepartmentList();
            //string[] courseArray = { "1st Semester", "2nd Semester", "3rd Semester", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semester" };
            // List<string> semesterList = aCourseManager.GetAllSemesters();
            //string[] array ={"1st Semester", "2nd Semester", "3rd Semester", "4th Semester", "5th Semester", "6th Semester", "7th Semester", "8th Semester"};
            //ViewBag.departmentCodeList = departmentCodeList;
            // ViewBag.semesterList = semesterList;
            List<DepartmentModel> departmentList = aCourseManager.GetDepartmentList();
            List<SemesterModel> semesterList = aCourseManager.GetAllSemesters();
            ViewBag.departmentList = departmentList;
            ViewBag.semesterList = semesterList;
            return View();
        }

        public JsonResult GetDepartments()
        {
            List<DepartmentModel> departments = new List<DepartmentModel>();
            departments = aCourseManager.GetDepartmentList();
            return Json(departments, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult ViewAllCourses(int? messageFromEdit)
        {
            List<CourseModel> courses = new List<CourseModel>();
            courses = aCourseManager.ViewAllCourses();
            if (courses.Count == 0)
            {
                string message = "No data in the database for courses";
                ViewBag.MessageViewCourses = message;
            }
            else if (messageFromEdit > 0)
            {
                ViewBag.MessageViewCourses = "Courses Updated Successfully";
            }
            ViewBag.CourseList = courses;
            return View();
        }


        [HttpGet]
        public ActionResult EditCourseFromList(int courseId, int? message)
        {
            if (message != null)
            {
                if (message == 0)
                {
                    ViewBag.Message = "Sorry! Course Update Failed !!";
                }
                else if (message == 5)
                {
                    ViewBag.Message = "Sorry! Course Code Exists !!";

                }
                else if (message == 6)
                {
                    ViewBag.Message = "Sorry! Course Name Exists !!";

                }

            }
            CourseModel aCourseModel = new CourseModel();
            aCourseModel = aCourseManager.GetCourseByCourseId(courseId);
            List<DepartmentModel> departments = aCourseManager.GetDepartmentList();


            List<SemesterModel> semesters = aCourseManager.GetAllSemesters();
            ViewBag.Depts = departments;
            ViewBag.Sems = semesters;
            return View(aCourseModel);
        }


        [HttpPost]
        public ActionResult EditCourseFromList(CourseModel aCourseModel)
        {
            //string message = "";
            int rowAffected;
            rowAffected = aCourseManager.UpdateCourse(aCourseModel);

            //ViewBag.Message2 = message;
            if (rowAffected == 1)
            {
                return RedirectToAction("ViewAllCourses", new { message = rowAffected });
            }
            else
            {
                return RedirectToAction("EditCourseFromList", new { courseId = aCourseModel.courseId, message = rowAffected });
            }
        }
        public ActionResult DeleteCourseFromList(int courseId)
        {

            int rowsEffected = aCourseManager.DeleteCourse(courseId);
            if (rowsEffected > 0)
            {
                return RedirectToAction("ViewAllCourses");
            }
            else
            {
                return null;
            }
        }

        [HttpGet]
        public ActionResult ViewCourseStatistics()
        {
            List<CourseStatisticsModel> courseStatisticsInfo = new List<CourseStatisticsModel>();
            //courseStatisticsInfo = aCourseManager.;
            if (courseStatisticsInfo.Count == 0)
            {
                string message = "No data in the database for courses";
                ViewBag.MessageViewCourses = message;
            }
            ViewBag.courseStatisticsList = courseStatisticsInfo;
            return View();
        }
    }
}

UniversityManagementSystem06/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem06.BusinessLogics.Department;
using UniversityManagementSystem06.Models;

namespace UniversityManagementSystem06.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();

        // GET: Department
        [HttpGet]
        public ActionResult SaveDepartment()
        {
            return View();
        }

        public ActionResult Try()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveDepartment(DepartmentModel aDepartmentModel)
        {
            string message = "";

            message = aDepartmentManager.SaveDepartment(aDepartmentModel);

            ViewBag.Message = message;

            return View();
        }

        [HttpGet]

        public ActionResult ViewDepartments(int? messageFromEdit)
        {
            List<DepartmentModel> departments = new List<DepartmentModel>();
            departments = aDepartmentManager.GetAllDepartments();
            if (departments.Count == 0)
            {
                //int d = departments.Count;
                string message = "No data in the database for Departments";
                ViewBag.MessageViewDepartments = message;
            }
            else if (messageFromEdit > 0)
            {
                ViewBag.MessageViewDepartments = "Department Updated Successfully";
            }
            ViewBag.DepartmentList = departments;
            //int i = 0;
            return View();
        }

        public JsonResult IsDeptCodeExists(string DeptCode)
        {
            bool isDeptCodeExists = aDepartmentManager.IsDepartmentCodeExist(DeptCode);

            if (isDeptCodeExists)
                return Json(false, JsonRequestBehavior.AllowGet);
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);

            }
        }

        public JsonResult IsDeptNameExists(string DeptName)
        {
            bool isDeptNameExists = aDepartmentManager.IsDepartmentNameExist(DeptName);

            if (isDeptNameExists)
                return Json(false, JsonRequestBehavior.AllowGet);
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpGet]
        public ActionResult EditDepartmentFromList(int departmentId, int? message)
        {
            if (message != null)
            {
                if (message == 0)
                {
                    ViewBag.Message = "Sorry! Department Update Failed !!";
                }
                else if (message == 5)
                {
                    ViewBag.Message = "Sorry! Department Code Exists !!";

                }
                else if (message == 6)
                {
                    ViewBag.Message = "Sorry! Department Name Exists !!";

                }

            }
            DepartmentModel aDepartmentModel = new DepartmentModel();
            aDepartmentModel = aDepartmentManager.GetDepartmentById(departmentId);
            return View(aDepartmentModel);
        }


        [HttpPost]
        public ActionResult EditDepartmentFromList(DepartmentModel aDepartmentModel)
        {
            //string message = "";
            int rowAffected;
            rowAffected = aDepartmentManager.UpdateDepartment(aDepartmentModel);

            //ViewBag.Message2 = message;
            if (rowAffected == 1)
            {
                return RedirectToAction("ViewDepartments", new { message = rowAffected });
            }
            else
            {
                return RedirectToAction("EditDepartmentFromList", new { departmentId = aDepartmentModel.DepartmentId, message = rowAffected });
            }
        }


        public ActionResult DeleteDepartmentFromList(int departmentId)
        {

            int rowsEffected = aDepartmentManager.DeleteDepartment(departmentId);
            if (rowsEffected > 0)
            {
                return RedirectToAction("ViewDepartments");
            }
            else
            {
                string msg = "Delete could not occur";
                return RedirectToAction("ViewDepartments", new { message = msg });
            }


        }
    }
}

UniversityManagementSystem06/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem06.BusinessLogics.Department;
using UniversityManagementSystem06.BusinessLogics.Teacher;
using UniversityManagementSystem06.Models;

namespace UniversityManagementSystem06.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        // GET: TeacherModel
        [HttpGet]
        public ActionResult SaveTeacher()
        {
            DepartmentManager aDepartmentManager = new DepartmentManager();
            List<DepartmentModel> departmentList = aDepartmentManager.GetAllDepartments();
            ViewBag.departments = departmentList;
            //string[] designationArray = { "Professor","Assistance Professor","Senior Teacher","Junior Teacher"};
            List<DesignationModel> designations = aTeacherManager.GetAllDesignations();
            ViewBag.designations = designations;
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(TeacherModel aTeacherModel)
        {


            //if (aTeacherModel.DesignationId == 0)
            //{
            //    ViewBag.Message = "Teacher Save Failed !! \n Designation is not selected";
            //}
            //else if (aTeacherModel.DepartmentId==0)
            //{
            //    ViewBag.Message = "Teacher Save Failed !! \n Designation is not selected";
            //}
            //else
            {
                string message = "";
                message = aTeacherManager.SaveTeacher(aTeacherModel);

                ViewBag.Message = message;
            }


            DepartmentManager aDepartmentManager = new DepartmentManager();
            List<DepartmentModel> departmentList = aDepartmentManager.GetAllDepartments();
            ViewBag.departments = departmentList;

            List<DesignationModel> designations = aTeacherManager.GetAllDesignations();
            ViewBag.designations = designations;

            return View();
        }

        [HttpGet]
        public ActionResult ViewAllTeachers(int? message)
        {
            List<TeacherModel> teachers = new List<TeacherModel>();
            teachers = aTeacherManager.GetAllTeachers();
            if (teachers.Count == 0)
            {
                string msg = "No data in the database for teachers";
                ViewBag.Message = msg;
            }
            else if (message > 0)
            {
                ViewBag.Message = "Teacher Updated Successfully";
            }
            ViewBag.TeacherList = teachers;
            return View();
        }


        [HttpGet]
        public ActionResult EditTeacherFromList(int teacherId, int? message)
        {
            //use modelstate.IsValid
            if (message != null)
            {
                if (message == 0)
                {
                    ViewBag.Message = "Sorry! Teacher Update Failed !!";
                }
                else if (message == 5)
                {
                    ViewBag.Message = "Sorry! Teacher Email Exists !!";
                }
            }
            TeacherModel aTeacherModel = new TeacherModel();
            aTeacherModel = aTeacherManager.GetTeacherByTeacherId(teacherId);

            List<DepartmentModel> depts = aTeacherManager.GetAllDepartments();
            List<DesignationModel> designations = aTeacherManager.GetAllDesignations();
            ViewBag.Depts = depts;
            ViewBag.Designations = designations;

            return View(aTeacherModel);
        }


        [HttpPost]
        public ActionResult EditTeacherFromList(TeacherModel aTeacherModel)
        {
            //string message = "";  
            int rowAffected;
            rowAffected = aTeacherManager.UpdateTeacher(aTeacherModel);

            //ViewBag.Message2 = message;
            if (rowAffected == 1)
            {
                return RedirectToAction("ViewAllTeachers", new { message = rowAffected });
            }
            else
            {
                return RedirectToAction("EditTeacherFromList", new { teacherId = aTeacherModel.TeacherId, message = rowAffected });
            }
        }




        public ActionResult DeleteTeacherFromList(int teacherId)
        {
            int rowsEffected = aTeacherManager.DeleteTeacher(teacherId);
            if (rowsEffected > 0)
            {
                return RedirectToAction("ViewAllTeachers");
            }
            else
            {
                return null;
            }
        }
    }
}

UniversityManagementSystem06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/simplex.bootstrap.css" rel="stylesheet" />
</head>


<body style="background-color:aliceblue">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@

    <div class=" fixed-top navbar-light bg-light">
        <ul class="nav nav-tabs" style="background-color:ghostwhite">
            <li class="nav-item">
                <a class="nav-link @*active*@" data-toggle="tab" href="#home">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#profile">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Department</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("SaveDepartment", "Department")">Save Department</a>
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item" href="@Url.Action("ViewDepartments", "Department")">View Departments</a>

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Course</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("SaveCourse", "Course")">Save Course</a>
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item" href="@Url.Action("ViewAllCourses", "Course")">View Courses</a>

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Teacher</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("SaveTeacher", "Teacher")">Save Teacher</a>
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item" href="@Url.Action("ViewAllTeachers", "Teacher")">View Teachers</a>

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Course Assign to Teacher</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("AssignTeacher", "CourseAssignToTeacher")">Assign Teacher</a>
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item" href="@Url.Action("ViewAllAssignedTeachers", "CourseAssignToTeacher")">View CourseAssigns</a>

                </div>
            </li>


        </ul>

    </div>

    <br />
    <br />

    <div class="container body-content" >
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        <div id="footer">
            <div class="navbar navbar-inner  navbar-fixed-bottom  ">
                <p class="muted credit form-group"><center> by Imtiaj Ahammad</center></p>
            </div>
        </div>
        </footer>*@
    </div>
    <footer>
        <div id="footer">
            <hr />
            <div class="navbar navbar-inner  navbar-fixed-bottom  ">
                <p class="muted credit form-group"><center>&copy;  by Imtiaj Ahammad</center></p>
            </div>
        </div>

    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>