UniversityManagementSystem06/Controllers/CourseAssignToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem06.BusinessLogics.CourseAssignLogics;
using UniversityManagementSystem06.Models;

namespace UniversityManagementSystem06.Controllers
{
    public class CourseAssignToTeacherController : Controller
    {
        // GET: CourseAssignToTeacher

        /// <summary>
        /// show all courseAssignedToTeachers 
        /// </summary>
        /// <param name="messageFromEdit">after saving or updating, this controller is been called. so the save/update message can be sent as parameter if i want</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ViewAllAssignedTeachers(int? messageFromEdit)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            List<CourseAssignToTeacherModel> CourseAssignToTeachers = new List<CourseAssignToTeacherModel>();
            CourseAssignToTeachers = aCourseAssignManager.GetAllCourseAssignedTeachers();
            //return View(CourseAssignToTeachers);
            if (CourseAssignToTeachers.Count == 0)
            {
                string message = "No data in the database for AssignedTeacher";
                ViewBag.MessageViewCourses = message;
            }
            else if (messageFromEdit > 0)
            {
                ViewBag.MessageViewCourses = "AssignedTeacher Updated Successfully";
            }
            ViewBag.CourseAssignToTeacherModelList = CourseAssignToTeachers;
            
            return View();
        }
        //public ActionResult ViewAllCourses(int? messageFromEdit)
        //{
        //    List<CourseModel> courses = new List<CourseModel>();
        //    courses = aCourseAssignManager.ViewAllCourses();
        //    if (courses.Count == 0)
        //    {
        //        string message = "No data in the database for courses";
        //        ViewBag.MessageViewCourses = message;
        //    }
        //    else if (messageFromEdit > 0)
        //    {
        //        ViewBag.MessageViewCourses = "Courses Updated Successfully";
        //    }
        //    ViewBag.CourseList = courses;
        //    return View();
        //}

        [HttpGet]
        public ActionResult AssignTeacher()
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            ViewBag.Departments = aCourseAssignManager.GetAllDepartments();
            ViewBag.Teachers = aCourseAssignManager.GetAllTeachers();
            ViewBag.CourseCodeList = aCourseAssignManager.GetAllCourseCodes();
            return View();
        }
        [HttpPost]
        public ActionResult AssignTeacher(CourseAssignToTeacherModel courseAssignToTeacherModel)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            ViewBag.Departments = aCourseAssignManager.GetAllDepartments();
            ViewBag.Teachers = aCourseAssignManager.GetAllTeachers();
            ViewBag.CourseCodeList = aCourseAssignManager.GetAllCourseCodes();
            //do the code to store in the database
            if (aCourseAssignManager.IsCourseExist(courseAssignToTeacherModel.CourseId))
            {
                ViewBag.Message = ("Course is already assigned");
            }
            else
            {
                int stored = aCourseAssignManager.SaveCourseAssignToTeacher(courseAssignToTeacherModel);
                if (stored == 1)
                {
                    ViewBag.Message = ("Course Assign to Teacher done successfully");
                }
                else
                {
                    ViewBag.Message = ("Course Assign to Teacher Error");
                }
            }

            return View();

            /* 
             1. one course should be assigned to one teacher only-done
             2. if teacher credit exceed, an dialog box with yes/no pop up and work accordingly
             3. remaining credit returning false count--done
             */
        }



        /// <summary>
        /// to get teacher list from Dept id
        /// </summary>
        /// <param name="deptId"></param>
        /// <returns></returns>
        public JsonResult GetTeacherByDeptId(int deptId)
        {            
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            List<TeacherModel> teachers = new List<TeacherModel>();
            teachers = aCourseAssignManager.GetTeachersByDeptId(deptId);
            //var teachers = db.Teachers.Where(m => m.DepartmentId == deptId).ToList();
            //return Json(teachers, JsonRequestBehavior.AllowGet);
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseListByDeptId(int deptId)
        {
            List<CourseModel> courseList = new List<CourseModel>();
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            courseList = aCourseAssignManager.GetCourseListByDeptId(deptId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// get teacher credit from teacher table
        /// </summary>
        /// <param name="teacherId"></param>
        /// <returns></returns>
        public JsonResult GetCreditByTeacherId(int teacherId)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            int creditToBeTaken = aCourseAssignManager.GetCreditByTeacherId(teacherId);
            return Json(creditToBeTaken, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// checks how much credits are remaining
        /// </summary>
        /// <param name="teacherId"></param>
        /// <returns>total remaining credit </returns>
        public JsonResult GetRemainingCreditByTeacherId(int teacherId)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            int creditToBeTaken = aCourseAssignManager.GetCreditByTeacherId(teacherId);
            int remainingCredit;
            int totalAssignedCredit = aCourseAssignManager.GetAssignedCreditByTeacherId(teacherId);
            if (totalAssignedCredit == 0)
            {
                remainingCredit = creditToBeTaken;
            }
            else if (totalAssignedCredit < creditToBeTaken)
            {
                remainingCredit = creditToBeTaken - totalAssignedCredit;
            }
            else
            {
                remainingCredit = creditToBeTaken - totalAssignedCredit;
            }
            return Json(remainingCredit, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// check if teacherAssignedCredit is more than the credit is being taken
        /// </summary>
        /// <param name="teacherID"></param>
        /// <param name="currentCreditTaking"></param>
        /// <returns></returns>
        public JsonResult CheckTakenCreditOverFlowsRemainingCredit(int teacherID, int currentCreditTaking)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            int creditToBeTaken = aCourseAssignManager.GetCreditByTeacherId(teacherID);
            int totalAssignedCredit = aCourseAssignManager.GetAssignedCreditByTeacherId(teacherID);
            totalAssignedCredit = totalAssignedCredit + currentCreditTaking;
            if (totalAssignedCredit > creditToBeTaken)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpPost]
        public JsonResult GetCourseModelByCourseId(int courseId)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            CourseModel aCourseModel = new CourseModel();
            aCourseModel = aCourseAssignManager.GetCourseModelByCourseId(courseId);
            return Json(aCourseModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditAssignedTeacher(int id, int? message)
        {
            if (message != null)
            {
                if (message == 0)
                {
                    ViewBag.Message = "Sorry! Course Assign Update Failed !!";
                }
                else if (message == 5)
                {
                    ViewBag.Message = "Sorry! Course Code Exists !!";

                }
                else if (message == 6)
                {
                    ViewBag.Message = "Sorry! Course Name Exists !!";

                }

            }

            CourseAssignManager aCourseAssignManager = new CourseAssignManager();
            ViewBag.Departments = aCourseAssignManager.GetAllDepartments();
            ViewBag.Teachers = aCourseAssignManager.GetAllTeachers();
            ViewBag.CourseCodeList = aCourseAssignManager.GetAllCourseCodes();


            CourseAssignToTeacherModel aCourseAssignToTeacherModel = new CourseAssignToTeacherModel();
            aCourseAssignToTeacherModel = aCourseAssignManager.GetAssignedCourseToTeacherModelById(id);



            /*ViewBag.Departments = aCourseAssignManager.GetAllDepartments();
            ViewBag.Teachers = aCourseAssignManager.GetAllTeachers();
            ViewBag.CourseCodeList = aCourseAssignManager.GetAllCourseCodes();*/
            return View(aCourseAssignToTeacherModel);
        }
        [HttpPost]
        public ActionResult EditAssignedTeacher(CourseAssignToTeacherModel courseAssignToTeacherModel)
        {
            return View();
        }

        /*[HttpGet]
        public ActionResult DeleteAssignedTeacher()
        {
            return View();
        }*/
        //[HttpPost]
        public ActionResult DeleteAssignedTeacher(int id)
        {
            CourseAssignManager aCourseAssignManager = new CourseAssignManager();

UniversityManagementSystem06/Views/CourseAssignToTeacher/AssignTeacher.cshtml
@{
    ViewBag.Title = "AssignTeacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var departments = ViewBag.Departments;
    var teachers = ViewBag.Teachers;
    var courseCodes = ViewBag.CourseCodeList;
}


<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="~/Scripts/jquery-2.2.4.min.js"></script>

</head>
<body>
    <div align="center">
        @if (ViewBag.Message != null)
        {
            <div id="msgId">  <span id="success-alert" class="text-danger">@ViewBag.Message</span> </div>
        }
    </div>
    <div>
        <form method="post" action="AssignTeacher" id="formId">
            <fieldset>
                <legend>Assign Course</legend>
                <div class="form-group">
                    <label for="exampleSelect1">Course Department</label>
                    <select class="form-control" id="departmentDropdownId" required name="departmentId">
                        <option value="0"></option>
                        @foreach (var a in departments)
                        {
                            <option value="@a.DepartmentId">@a.DepartmentName</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleSelect1">Teacher</label>
                    <select class="form-control" id="teacherDropdownId" required name="TeacherId">
                        <option value="0"></option>
                        @foreach (var a in teachers)
                        {
                            <option value="@a.TeacherId">@a.TeacherName</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Credit to be taken:</label>
                    <input type="text" class="form-control" aria-describedby="emailHelp" name="TeacherCreditToBeTaken" readonly id="creditTakenInputId" required>
                    <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Remaining Credit:</label>
                    <input type="text" class="form-control" aria-describedby="emailHelp" name="TeacherRemainingCredit" readonly id="remainingCreditInputId" required>
                    <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
                </div>
                <div class="form-group">
                    <label for="exampleSelect1">Course Code:</label>
                    <select class="form-control" id="courseCodeDropdownId" required name="CourseId">
                        <option value="0"></option>
                        @foreach (var a in courseCodes)
                        {
                            <option value="@a.courseId">@a.courseCode</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp" readonly id="courseNameId" required>
                    <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Credit</label>
                    <input type="tel" class="form-control" aria-describedby="emailHelp" readonly id="courseCreditId" required>
                    <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
                </div>
                <button type="submit" class="btn btn-info">Submit</button>
                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("ViewAllAssignedTeachers", "CourseAssignToTeacher")'">View List</button>
            </fieldset>
        </form>
    </div>
</body>
</html>


<script type='text/javascript'>
    $(function () {

        $("#departmentDropdownId").change(function () {//for every change course other options should be changed
            //debugger;
            var departmentId = $("#departmentDropdownId").val();
            if (departmentId == null || departmentId == "") {
                //alert(departmentId + "+NULL");
                $("#teacherDropdownId").empty();
                $("#creditTakenInputId").val("");
                $("#remainingCreditInputId").val("");
                $("#courseCodeDropdownId").empty();
                $("#courseNameId").val("");
                $("#courseCreditId").val("");
            }
            else {
                $("#teacherDropdownId").empty();
                $("#creditTakenInputId").val("");
                $("#remainingCreditInputId").val("");
                $("#courseCodeDropdownId").empty();
                $("#courseNameId").val("");
                $("#courseCreditId").val("");
                //alert(departmentId + "+ELSE")
                var jasonData = { deptId: departmentId };
                //debugger;
            $.ajax({//to get the list of teachers from selected department
                    type: "POST",
                    url: '@Url.Action("GetTeacherByDeptId", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jasonData),
                    dataType: "json",
                success: function (data) {
                    $("#teacherDropdownId").append('<option value=' +'' +  '>' + "Select Teacher" + '</option>');
                    $.each(data, function (key, value) {
                        $("#teacherDropdownId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                    });
                },
                failure: function (response) { alert(response.d + "hello"); },
                error: function (response) { alert(response.d +  "hello2"); }
            });//return false;
            $.ajax({//to get the course id according to chosen department
                    type: "POST",
                    url: '@Url.Action("GetCourseListByDeptId", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jasonData),
                    dataType: "json",
                success: function (data) {
                    $("#courseCodeDropdownId").append('<option value=' + '' +  '>' + "Select Course Code" + '</option>');
                    $.each(data, function (key, value) {
                        $("#courseCodeDropdownId").append('<option value=' + value.courseId + '>' + value.courseCode + '</option>');
                    });
                },
                failure: function (response) { alert(response.d); },
                error: function (response) { alert(response.d); }
            });//return false;
            }

        });

        $("#teacherDropdownId").change(function () {
           // to  fill the input field "Credit to be taken:" & "Remaining Credit:"
            //$("#creditTakenInputId").empty();
            //$("#remainingCreditInputId").empty();
            ///var teacher = $("#teacherDropdownId :selected").text();
            var teacherIdd = $("#teacherDropdownId").val();
            //debugger;
            if (teacherIdd == null || teacherIdd=="") {

                //alert(teacherIdd +"null");
                $("#creditTakenInputId").val("");
                $("#remainingCreditInputId").val("");
            }
            else {
                $("#creditTakenInputId").val("");
                $("#remainingCreditInputId").val("");
                //alert(teacherIdd+ " else ");
            var jasonData = { teacherId: teacherIdd };
            var teacherCreditToBeTaken = 0;
            var remainingCredit = 0;
                $.ajax({ // to get the credit to be taken for a teacher
                type: "POST",
                        url: '@Url.Action("GetCreditByTeacherId", "CourseAssignToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jasonData),
                        dataType: "json",
                    success: function (data) {
                    //alert("me " + data);
                    teacherCreditToBeTaken = data;
                        //alert(teacherCreditToBeTaken);
                        $("#creditTakenInputId").val(data);
                },
                    failure: function (response) { alert(response.d); },
                    error: function (response) { alert(response.d); }
            });
            var jasonData2 = { teacherId: teacherIdd};
                $.ajax({// for remaining credit
                        type: "POST",
                        url: '@Url.Action("GetRemainingCreditByTeacherId", "CourseAssignToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jasonData2),
                        dataType: "json",
                    success: function (data) {
                        remainingCredit = parseInt(data);
                        //alert(remainingCredit = parseInt(data));
                        $("#remainingCreditInputId").val(remainingCredit);
                    },
                    failure: function (response) { alert(response.d); },
                    error: function (response) { alert(response.d); }
                });
            }

        });

        $("#courseCodeDropdownId").change(function () {// to fill up Name & Credit according to courseCode dropdown
            //debugger;
            //$("#courseNameId").val("");
            //$("#courseCreditId").val("");
            ///var teacher = $("#teacherDropdownId :selected").text();
            var courseIdd = $("#courseCodeDropdownId").val();
                //alert($("#teacherDropdownId :selected").text());
            if (courseIdd == null || courseIdd == "") {
                $("#courseNameId").val("");
                $("#courseCreditId").val("");
            }
            else {
                $("#courseNameId").val("");
                $("#courseCreditId").val("");
                            var courseName = "";
                var courseCredit = 0;
                var jasonData = { courseId: courseIdd };
                $.ajax({// to get courseName & courseCredit
                type: "POST",
                        url: '@Url.Action("GetCourseModelByCourseId", "CourseAssignToTeacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jasonData),
                        dataType: "json",
                    success: function (data) {
                    //alert("me " + data);
                    teacherCreditToBeTaken = data;
                        //alert(teacherCreditToBeTaken);
                        courseName = data.courseName;
                        courseCredit = data.courseCredit;

                        $("#courseNameId").val(data.courseName);
                        $("#courseCreditId").val(data.courseCredit);
                },
                    failure: function (response) { alert(response.d); },
                    error: function (response) { alert(response.d); }
            });
            }
        });
    });

</script>

UniversityManagementSystem06/Views/CourseAssignToTeacher/EditAssignedTeacher.cshtml
@{
    ViewBag.Title = "EditAssignedTeacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var departments = ViewBag.Departments;
    var teachers = ViewBag.Teachers;
    var courseCodes = ViewBag.CourseCodeList;
}

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <br />
    <br />
    <div align="center">
        @if(ViewBag.Message != null)
        {
            <span id="success-alert" class="">@ViewBag.Message</span>
        }
    </div>
    <br />
    <form method="post" action="EditAssignedTeacher">
        <fieldset>
            <legend>Edit Assigned Course</legend>
            <input type="hidden" name="courseId" value="@Model.CourseAssignToTeacherId" />
            <div class="form-group">
                <label for="exampleSelect1">Course Department</label>
                <select class="form-control" id="exampleSelect1" required name="departmentId">
                    <option value="0"></option>
                    @foreach (var a in departments)
                    {
                        if (a.DepartmentId == Model.DepartmentId)
                        {
                            <option selected value="@a.DepartmentId">@a.DepartmentName</option>
                        }
                        else
                        {
                            <option value="@a.DepartmentId">@a.DepartmentName</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="exampleSelect1">Course Teacher</label>
                <select class="form-control" id="exampleSelect1" required name="TeacherId">
                    <option value="0"></option>
                    @foreach (var a in teachers)
                    {
                        if (a.TeacherId == Model.TeacherId)
                        {
                            <option selected value="@a.TeacherId">@a.TeacherName</option>
                        }
                        else
                        {
                            <option value="@a.TeacherId">@a.TeacherName</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Credit to be taken:</label>
                <input type="text" class="form-control" aria-describedby="emailHelp" name="TeacherCreditToBeTaken" readonly id="creditTakenInputId" required value="@Model.Teacher.TeacherCreditToBeTaken">
                <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Remaining Credit:</label>
                <input type="text" class="form-control" aria-describedby="emailHelp" name="TeacherRemainingCredit" readonly id="remainingCreditInputId" required value="@Model.TeacherRemainingCredit">
                <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
            </div>
            <div class="form-group">
                <label for="exampleSelect1">Course Code</label>
                <select class="form-control" id="exampleSelect1" required name="CourseId">
                    <option value="0"></option>
                    @foreach (var a in courseCodes)
                    {
                        if (a.courseId == Model.CourseId)
                        {
                            <option selected value="@a.courseId">@a.courseCode</option>
                        }
                        else
                        {
                            <option value="@a.courseId">@a.courseCode</option>
                        }
                    }
                </select>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="email" class="form-control" aria-describedby="emailHelp" readonly id="courseNameId" required value="@Model.Course.courseName" >
                <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Credit</label>
                <input type="tel" class="form-control" aria-describedby="emailHelp" readonly id="courseCreditId" required value="@Model.Course.courseCredit" >
                <small id="emailHelp" class="form-text text-muted fade">Code must be at least 5 characters long</small>
            </div>



            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("ViewAllAssignedTeachers", "CourseAssignToTeacher")'">View List</button>
            <button type="submit" class="btn btn-info">Submit</button>



        </fieldset>
    </form>


</body>

</html>